services:
  - type: web
    name: ai-learning-platform
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-learning-backend-707v.onrender.com
