import { Injectable } from '@nestjs/common';
import OpenAI from 'openai';

@Injectable()
export class AiService {
  private openai: OpenAI;

  constructor() {
    this.openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }

  async generateLesson(category: string, subCategory: string, prompt: string): Promise<string> {
    try {
      const completion = await this.openai.chat.completions.create({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: `You are an expert teacher in ${category}, specifically ${subCategory}. Provide clear, educational, and engaging lessons.`,
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        max_tokens: 500,
        temperature: 0.7,
      });

      return completion.choices[0]?.message?.content || 'Unable to generate lesson.';
    } catch (error) {
      console.error('OpenAI API Error:', error);
      return `This is a mock lesson about ${prompt} in ${category} - ${subCategory}. In production, this would be generated by OpenAI GPT.`;
    }
  }
}
